### PR TITLE
Remove extraneous text from readme.md

### PR DESCRIPTION
**Pull request by johnhenry**

### CODE REVIEW

**Comment by DougAnderson444** [comment]
Thanks for the PR. But you do need this entire text line to build the `ipfs-core` files into the `es modules`. Without it, `esbuild` wouldn't know what to bundle

**Comment by DougAnderson444** [comment]
I see what you're saying, it should be:

```
npm run build:ipfs
```

**Review by DougAnderson444 — COMMENTED** [review]
I see what you're saying, it should be:

```
npm run build:ipfs
```

**Comment by johnhenry** [comment]
@DougAnderson444 Thanks for putting this together! It was helpful!

**Pull request merged**
